var messages = [["You are Braver than you believe, Stronger than you seem, and Smarter than you think.", "Christopher Robin"],
["Don't ever let a soul in the world tell you that you can't be exactly who you are.", "Lady Gaga"],
["Our greatest glory is not in never falling, but in rising every time we fall.", "Confucius"],
["Be strong now, because things will get better. It might be stormy now, but it can't rain forever.", "Anonymous"],
["If plan A doesn't work, the alphabet has 25 more letters , 204 if you're in Japan.", "Claire Cook"],
["Despite the forecast, live like it's spring.", "Lily Pulitzer"],
["Don't stop because you're tired. Keep going because you're almost there.", "Anonymous"],
["Believe you can and you’re halfway there.", "Theodore Roosevelt"],
["You were born to be real, not to be perfect.", "Ralph Marston"],
["The ultimate measure of a man is not where he stands in moments of comfort and convenience but where he stands in times of challenge and controversy.", "Martin Luther King Jr."],
["What lies behind us and what lies ahead of us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"],
["Be thankful for what you have; you’ll end up having more. If you concentrate on what you don’t have, you will never, ever have enough.", "Oprah Winfrey"],
["Trees that are slow to grow bear the best fruit.", "Molière, Playwright"]
["Today was good. Today was fun. Tomorrow is another one.", "Dr. Seuss"],
["Nothing is impossible, the word itself says “I’m possible”", "Audrey Hepburn"],
["When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.", "Henry Ford"],
["When I hear somebody sigh, ‘Life is hard,’ I am always tempted to ask, ‘Compared to what?", "Sydney Harris"],
["What we achieve inwardly will change outer reality.", "Plutarch"],
["The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"],
["Remember that not getting what you want is sometimes a wonderful stroke of luck.", "Dalai Lama"],
["Experience is simply the name we give our mistakes.", "Oscar Wilde"],
["If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", "Martin Luther King Jr."],
["Failure is the condiment that gives success its flavor." , "Truman Capote"],
["You have power over your mind , not outside events. Realize this, and you will find strength." , "Marcus Aurelius"],
["Pain is temporary. Quitting lasts forever." , "Lance Armstrong"],
["It does not matter how slowly you go as long as you do not stop." , "Confucius"],
["Always dream and shoot higher than you know you can do. Do not bother just to be better than your contemporaries or predecessors. Try to be better than yourself." , "William Faulkner"],
["Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope." , "Maya Angelou"],
["There is a crack in everything, that's how the light gets in." , "Leonard Cohen"],
["If you hear a voice within you say 'you cannot paint,' then by all means paint, and that voice will be silenced." , "Vincent Van Gogh"],
["Never confuse a single defeat with a final defeat." , "F. Scott Fitzgerald"],
["Practice isn't the thing you do once you're good. It's the thing you do that makes you good." , "Malcolm Gladwell"],
["You may encounter many defeats, but you must not be defeated. Please remember that your difficulties do not define you. They simply strengthen your ability to overcome." , "Maya Angelou"],
["Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway." , "Earl Nightingale"],
["Our greatest glory is not in never falling, but in rising every time we fall." , "Confucius"],
["Don't watch the clock; do what it does. Keep going." , "Sam Levenson"],
["The most important thing in life is to stop saying 'I wish' and start saying 'I will.' Consider nothing impossible, then treat possibilities as probabilities." , "Charles Dickens"],
["Failure should be our teacher, not our undertaker. Failure is delay, not defeat. It is a temporary detour, not a dead end. Failure is something we can avoid only by saying nothing, doing nothing, and being nothing." , "Denis Waitley"],
["Other people's opinion of you does not have to become your reality." , "Les Brown"],
["You don't have to be a hero to accomplish great things—,to compete. You can just be an ordinary chap, sufficiently motivated to reach challenging goals." , "Edmund Hillary"],
["Don't let yesterday use up too much of today." , "Will Rogers"],
["You're off to Great Places! Today is your day! Your mountain is waiting, So... get on your way!" , "Dr. Seuss"],
["Keep your face always toward the sunshine , and shadows will fall behind you." , "Walt Whitman"],
["When everything seems to be going against you, remember that the airplane takes off against the wind, not with it." , "Henry Ford"],
["Life doesn't require that we be the best, only that we try our best." , "H. Jackson Brown Jr"],
["Suppose you were an idiot, and suppose you were a member of Congress; but I repeat myself." , "Mark Twain"],
["Don't judge each day by the harvest you reap but by the seeds that you plant." , "Robert Louis Stevenson"],
["Life has no meaning. Each of us has meaning and we bring it to life. It is a waste to be asking the question when you are the answer." , "Joseph Campbell"],
["The first and the best victory is to conquer self." , "Plato 🍽"],
["Winning is great, sure, but if you are really going to do something in life, the secret is learning how to lose. Nobody goes undefeated all the time. If you can pick up after a crushing defeat, and go on to win again, you are going to be a champion someday." , "Wilma Rudolph"]
]

function generator() {
    var randomNumber = Math.floor(Math.random() * messages.length)
    document.getElementById("messageContainer").innerHTML = "\"" + messages[randomNumber][0] + "\"" + "<br>" + "-" + "<b>" +  messages[Math.floor(randomNumber)][1] + "</b>";;;
   }